name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-29"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzlmYTdhMDktZGRlMS00MzRhLTkyY2ItOTE2MjYwMzcyNWEzIiwidGVuYW50X2lkIjoiNTE5YjU4NWYyZmM3Y2M1YmM2NDU5NTQ1NmJmZjBkMzRmYTgwZjYxYmJiZjBhNDAzOTM3MzUzZjRkNjk3ZjdiZiIsImludGVybmFsX3NlY3JldCI6Ijc0ZTYyZjViLThlMTAtNDI5YS1iZDQxLTgyNzRlMDY2Y2NjNCJ9.kyDKV0evv_7gwOyzlKvzT1C-BNo9Rta3ocFlG4gQwpQ"

JWT_SECRET = "DO TRADING & FREELANCING BITCH"